name: Automatic generate changelog

on:
  push:
    branches: [develop, master, tags]

jobs:
  generate_CHANGELOG:
    name: Generate and commit changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install -g auto-changelog
      - run: npm run changelog --if-present

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Workflow
          author_email: contato@tiagoboeing.com
          message: "[Automatic] Changelog generated"
          add: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN_GITHUB}}
